CREATE EXTENSION IF NOT EXISTS vector;

DROP TABLE IF EXISTS log_chunks;
DROP TABLE IF EXISTS incidents;


CREATE TABLE log_chunks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source      TEXT NOT NULL,
    service     TEXT,
    environment TEXT,
    severity    TEXT,
    event_time  TIMESTAMPTZ NOT NULL,
    occurrences INTEGER NOT NULL DEFAULT 1,
    first_seen  TIMESTAMPTZ,
    last_seen   TIMESTAMPTZ,
    content     TEXT NOT NULL,
    embedding   VECTOR(1536),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX log_chunks_embedding_hnsw_idx
    ON log_chunks USING hnsw (embedding vector_cosine_ops);
CREATE INDEX log_chunks_service_env_time_idx
    ON log_chunks (service, environment, event_time);


CREATE TABLE incidents (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signature   TEXT UNIQUE NOT NULL,
    service     TEXT,
    environment TEXT,
    sources     TEXT[] NOT NULL DEFAULT '{}',
    severity    TEXT NOT NULL DEFAULT 'warn',
    status      TEXT NOT NULL DEFAULT 'open',
    title       TEXT NOT NULL,
    summary     TEXT,
    error_count INTEGER NOT NULL DEFAULT 0,
    warn_count  INTEGER NOT NULL DEFAULT 0,
    sample_log  TEXT,
    first_seen  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX incidents_status_last_seen_idx
    ON incidents (status, last_seen DESC);



